import type { Metadata } from "next";

import { seoConfig } from "@/config/seo";
import type { IaPageDefinition, IaPageKey } from "@/types/information-architecture";

const pageDefinitions: Record<IaPageKey, IaPageDefinition> = {
  home: {
    key: "home",
    title: "Home",
    path: "/",
    purpose: "Introduce Neeraj Singh Rajput, establish credibility, and route visitors to contact or project pages.",
    targetAudience: "Clients, startups, and teams looking for a MERN stack or React Native developer.",
    conversionGoal: "Move users to Book Meeting or Estimate Project.",
    components: ["Hero", "Trust Logos", "Services Preview", "Personal Products Glimpse", "CTA"],
    seoStrategy:
      "Target core commercial intent keywords, ItemList schema for personal products, and internal links to product and service hubs.",
  },
  about: {
    key: "about",
    title: "About",
    path: "/about",
    purpose:
      "Present Neeraj Singh Rajput's full profile — name, role, summary, experience, education, journey, and skills.",
    targetAudience: "Prospects validating credibility, fit, and depth of experience.",
    conversionGoal: "Drive visitors to Contact, Projects, and Personal Products.",
    components: [
      "Profile Hero",
      "Experience Timeline",
      "Education",
      "Career Journey",
      "Skills & Principles",
      "CTA",
    ],
    seoStrategy:
      "Optimize for branded trust queries and Person schema with alumni, skills, and contact entity signals.",
  },
  services: {
    key: "services",
    title: "Services",
    path: "/services",
    purpose: "Present all service offerings with clear outcomes and engagement models.",
    targetAudience: "Buyers looking for specific execution capabilities.",
    conversionGoal: "Push to Service Detail pages and Estimate Project.",
    components: ["Service Grid", "Outcome Blocks", "Delivery Models", "FAQ", "CTA"],
    seoStrategy: "Use high-intent service keywords and route traffic to long-tail service detail pages.",
  },
  projects: {
    key: "projects",
    title: "Projects & Personal Products",
    path: "/projects",
    purpose:
      "Showcase personal products available to buy or license, plus company and client delivery with clear category filters.",
    targetAudience:
      "Buyers looking for ready products, and prospects comparing portfolio relevance to their goals.",
    conversionGoal: "Open personal product pages, live demos, and contact flow.",
    components: ["Category Filter Tabs", "Personal Product Cards", "Company Work Cards", "Tags", "Live Links"],
    seoStrategy:
      "Index every project page, emphasize personal-product ItemList schema, and cluster internal links to product detail URLs.",
  },
  caseStudies: {
    key: "caseStudies",
    title: "Case Studies",
    path: "/case-studies",
    purpose: "Show measurable business impact and delivery method in depth.",
    targetAudience: "High-intent prospects requiring proof before a call.",
    conversionGoal: "Book a strategy meeting.",
    components: ["Result Highlights", "Challenge-Solution-Impact", "KPI Panels", "CTA"],
    seoStrategy: "Target outcome-focused long-tail terms and enrich with case-study schema hints.",
  },
  aiSolutions: {
    key: "aiSolutions",
    title: "AI Solutions",
    path: "/ai-solutions",
    purpose: "Present technical integration capabilities — APIs, payment gateways, cloud services, and databases.",
    targetAudience: "Teams needing backend integrations, payment systems, or cloud deployment.",
    conversionGoal: "Start Estimate Project or Book Meeting.",
    components: ["Solution Categories", "Use-Case Matrix", "Stack Notes", "Risk Controls"],
    seoStrategy: "Capture AI service intent terms and route readers into specialized conversion pages.",
  },
  blog: {
    key: "blog",
    title: "Blog",
    path: "/blog",
    purpose: "Build authority and attract organic traffic through practical insights.",
    targetAudience: "Product builders, founders, and technical decision-makers.",
    conversionGoal: "Newsletter signups and service page clicks.",
    components: ["Featured Post", "Article Feed", "Category Filters", "Subscribe CTA"],
    seoStrategy: "Cluster content by pillar topics and optimize metadata per article intent.",
  },
  resources: {
    key: "resources",
    title: "Resources",
    path: "/resources",
    purpose: "Offer downloadable templates and tactical assets that create qualified leads.",
    targetAudience: "Mid-funnel users seeking practical frameworks and tools.",
    conversionGoal: "Lead capture and follow-up consultations.",
    components: ["Resource Library", "Format Filters", "Download Cards", "Lead Form"],
    seoStrategy: "Target template/checklist/guide keyword sets and enrich with internal topic links.",
  },
  testimonials: {
    key: "testimonials",
    title: "Testimonials",
    path: "/testimonials",
    purpose: "Increase confidence with social proof and outcome-based endorsements.",
    targetAudience: "Late-stage buyers comparing options before reaching out.",
    conversionGoal: "Book Meeting.",
    components: ["Quote Cards", "Client Logos", "Video/Testimonial Slider", "Impact Tags"],
    seoStrategy: "Strengthen trust signals and support conversion-focused branded queries.",
  },
  pricing: {
    key: "pricing",
    title: "Pricing",
    path: "/pricing",
    purpose: "Clarify engagement options, scope ranges, and expected investment.",
    targetAudience: "Budget-conscious buyers wanting transparent packages.",
    conversionGoal: "Choose an engagement and continue to Estimate Project.",
    components: ["Pricing Tiers", "Scope Matrix", "Add-Ons", "Pricing FAQ", "CTA"],
    seoStrategy: "Target pricing intent keywords and include structured FAQ coverage.",
  },
  contact: {
    key: "contact",
    title: "Contact",
    path: "/contact",
    purpose: "Provide direct communication path for custom inquiries.",
    targetAudience: "Any qualified visitor with project or partnership interest.",
    conversionGoal: "Submit contact form.",
    components: ["Contact Form", "Contact Channels", "Response SLA", "Trust Notes"],
    seoStrategy: "Optimize for brand + contact intent and maintain local/business metadata.",
  },
  bookMeeting: {
    key: "bookMeeting",
    title: "Book Meeting",
    path: "/book-meeting",
    purpose: "Convert qualified prospects into scheduled discovery calls.",
    targetAudience: "High-intent decision-makers ready for discussion.",
    conversionGoal: "Calendar booking completion.",
    components: ["Calendar Embed", "Qualification Prompts", "Meeting Prep", "Confirmation"],
    seoStrategy: "Focus on conversion clarity; optionally noindex if used as a campaign landing endpoint.",
  },
  faq: {
    key: "faq",
    title: "FAQ",
    path: "/faq",
    purpose: "Resolve common objections around process, pricing, and delivery.",
    targetAudience: "Prospects needing confidence before commitment.",
    conversionGoal: "Route users to Estimate Project or Book Meeting.",
    components: ["FAQ Accordion", "Category Tabs", "Inline CTAs", "Support Escalation"],
    seoStrategy: "Use question-led copy and FAQ structured data coverage.",
  },
  privacy: {
    key: "privacy",
    title: "Privacy",
    path: "/privacy",
    purpose: "Communicate data handling standards and legal transparency.",
    targetAudience: "Users and enterprise stakeholders reviewing compliance posture.",
    conversionGoal: "Trust retention and legal clarity.",
    components: ["Policy Sections", "Data Rights", "Retention Notes", "Contact Details"],
    seoStrategy: "Maintain indexable legal content with accurate metadata and canonical linking.",
  },
  terms: {
    key: "terms",
    title: "Terms",
    path: "/terms",
    purpose: "Define contractual boundaries, liabilities, and usage conditions.",
    targetAudience: "Clients, legal reviewers, and platform users.",
    conversionGoal: "Reduce legal friction before agreement.",
    components: ["Terms Sections", "Billing Terms", "IP Clauses", "Support Contact"],
    seoStrategy: "Keep indexable legal content for trust and policy completeness.",
  },
  dashboard: {
    key: "dashboard",
    title: "Dashboard",
    path: "/dashboard",
    purpose: "Give active clients a single source of truth for projects and collaboration.",
    targetAudience: "Authenticated clients and stakeholders.",
    conversionGoal: "Increase retention and project momentum.",
    components: ["Project Status", "Milestones", "Messages", "Files", "Invoices"],
    seoStrategy: "Noindex and auth-gated route with strong UX performance.",
  },
  admin: {
    key: "admin",
    title: "Admin",
    path: "/admin",
    purpose: "Centralize internal operations for leads, content, and delivery workflows.",
    targetAudience: "Site administrator managing blog content.",
    conversionGoal: "Operational efficiency and quality control.",
    components: ["Lead Queue", "Content Manager", "Project Ops", "Analytics Console"],
    seoStrategy: "Noindex, private access only, and strict role-based controls.",
  },
  projectDetail: {
    key: "projectDetail",
    title: "Project Detail",
    path: "/projects/[slug]",
    purpose: "Show deep context for each portfolio item with execution and impact details.",
    targetAudience: "Visitors comparing project relevance to their own use case.",
    conversionGoal: "Move to Contact or Book Meeting.",
    components: ["Project Hero", "Objectives", "Approach", "Tech Stack", "Results", "Next CTA"],
    seoStrategy: "Unique slug metadata and long-tail domain + stack keyword targeting.",
  },
  blogDetail: {
    key: "blogDetail",
    title: "Blog Detail",
    path: "/blog/[slug]",
    purpose: "Deliver a complete article experience and route readers deeper into the funnel.",
    targetAudience: "Organic traffic and subscribed readers.",
    conversionGoal: "Newsletter signup and service CTA click-through.",
    components: ["Article Body", "TOC", "Author Block", "Related Posts", "Inline CTA"],
    seoStrategy: "Article schema, rich metadata, and strong internal linking between topic clusters.",
  },
  serviceDetail: {
    key: "serviceDetail",
    title: "Service Detail",
    path: "/services/[slug]",
    purpose: "Explain one service deeply with process, scope, and expected outcomes.",
    targetAudience: "Prospects with a specific problem to solve.",
    conversionGoal: "Estimate Project submission.",
    components: ["Service Overview", "Deliverables", "Timeline", "Pricing Anchor", "FAQ", "CTA"],
    seoStrategy: "Long-tail service intent targeting with conversion-oriented copy blocks.",
  },
  estimateProject: {
    key: "estimateProject",
    title: "Estimate Project",
    path: "/estimate-project",
    purpose: "Collect structured scope details to generate early project qualification.",
    targetAudience: "Qualified leads prepared to discuss budget, timeline, and scope.",
    conversionGoal: "Multi-step estimate submission and booking handoff.",
    components: ["Multi-Step Form", "Scope Inputs", "Budget Range", "Summary", "Handoff CTA"],
    seoStrategy: "Optimize for conversion intent and optionally noindex if purely utility-driven.",
  },
  aiAssistant: {
    key: "aiAssistant",
    title: "AI Assistant",
    path: "/ai-assistant",
    purpose: "Offer interactive guidance and routing into the right service path.",
    targetAudience: "Visitors unsure which service or workflow best fits their need.",
    conversionGoal: "Assistant session completion and CTA handoff to estimate or booking.",
    components: ["Chat Surface", "Prompt Suggestions", "Recommendation Cards", "CTA Handovers"],
    seoStrategy: "Use intent-rich intro content and internal links while tracking assisted conversions.",
  },
};

export const iaPages = Object.values(pageDefinitions);

export function getIaPage(key: IaPageKey): IaPageDefinition {
  return pageDefinitions[key];
}

export function createIaMetadata(key: IaPageKey): Metadata {
  const page = pageDefinitions[key];
  return {
    title: `${page.title} | ${seoConfig.siteName}`,
    description: page.purpose,
    alternates: { canonical: page.path },
  };
}
